<?php

function gpx_field_theme($existing, $type, $theme, $path) {
  return [
    'gpx_stats' => [
      'variables' => [
        'elevation' => NULL,
        'demotion' => NULL,
        'lowest_point' => NULL,
        'highest_point' => NULL,
        'distance' => NULL,
        'points' => NULL,
        'elevation_profile' => NULL,
      ],
    ],
    'gpx_download' => [
      'variables' => [
        'gpx_file_url' => NULL
      ]
    ]
  ];
}